### ISSUE TITLE
TypeScript JSX ElementType broken in 3.0.x

### ISSUE THREAD

**Issue by joshkel** [ueberdosis/tiptap#6622]
### Affected Packages

core, react

### Version(s)

3.0.1

### Bug Description

After upgrading from Tiptap 2.26.1 to 3.0.1, my TypeScript React code that uses React's `ElementType` started failing with errors similar to the following:

```
src/Editor.tsx:10:11 - error TS2604: JSX element type 'Component' does not have any construct or call signatures.

10   return <Component />;
             ~~~~~~~~~

src/Editor.tsx:10:11 - error TS2786: 'Component' cannot be used as a JSX component.
  Its type 'React.ElementType' is not a valid JSX element type.
    Type 'number' is not assignable to type 'ElementType'.

10   return <Component />;
             ~~~~~~~~~
```

Here's the code that demonstrates this error:
```
interface Props {
  component: ElementType;
}

export function Test({ component: Component }: Props): ReactElement {
  return <Component />;
}
```

### Browser Used

Chrome

### Code Example URL

https://github.com/joshkel/tiptap-jsx-element-bug

### Expected Behavior

No errors

### Additional Context (Optional)

I believe that the problem is caused by [these types within jsx-runtime.ts](https://github.com/ueberdosis/tiptap/blob/v3.0.0-beta.24/packages/core/src/jsx-runtime.ts#L16):

```ts
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // @ts-ignore - conflict with React typings
    type Element = [string, ...any[]]
    // @ts-ignore - conflict with React typings
    interface IntrinsicElements {
      // @ts-ignore - conflict with React typings
      [key: string]: any
    }
  }
}
```

Those are merged with the types provided by @types/react (and throw errors if TypeScript's [`skipLibCheck` option](https://www.typescriptlang.org/tsconfig/#skipLibCheck) isn't enabled), resulting in `ElementType` being something that TypeScript thinks isn't compatible with JSX.

### Dependency Updates

- [x] Yes, I've updated all my dependencies.

**Comment by bdbch** [comment]
Will take a look into this!

**Comment by igortas** [comment]
Similar issue on my side, breaks every usage of ```JSX.Element```:
```
 ERROR(TypeScript)  Type 'import(".../node_modules/.pnpm/@types+react@19.1.8/node_modules/@types/react/jsx-runtime").JSX.Element' is not assignable to type 'JSX.Element'.
```

**Comment by bdbch** [comment]
This should be resolved with 3.0.3
