### ISSUE TITLE
[Bug]: build error version ^2.2.4

### ISSUE THREAD

**Issue by nur-sasongko** [ueberdosis/tiptap#5477]
### Affected Packages

tiptap

### Version(s)

2.2.4

### Bug Description

Here's my package.json version :
    "@tiptap/extension-bullet-list": "^2.2.4",
    "@tiptap/extension-color": "^2.2.4",
    "@tiptap/extension-heading": "^2.2.4",
    "@tiptap/extension-image": "^2.2.4",
    "@tiptap/extension-link": "^2.2.4",
    "@tiptap/extension-list-item": "^2.2.4",
    "@tiptap/extension-placeholder": "^2.2.4",
    "@tiptap/extension-text-align": "^2.2.4",
    "@tiptap/extension-text-style": "^2.2.4",
    "@tiptap/extension-underline": "^2.2.4",
    "@tiptap/extension-youtube": "^2.2.4",
    "@tiptap/pm": "^2.2.4",
    "@tiptap/react": "^2.2.4",
    "@tiptap/starter-kit": "^2.2.4",

RUN npm run build  :
src/components/atoms/TextEditor/TextEditor.tsx(381,24): error TS2322: Type 'import("/app/node_modules/@tiptap/core/dist/packages/core/src/Editor").Editor | null' is not assignable to type 
'import("/app/node_modules/@tiptap/react/dist/packages/react/src/Editor").Editor | null'.
  Property 'contentComponent' is missing in type 'import("/app/node_modules/@tiptap/core/dist/packages/core/src/Editor").Editor' but required in type 'import("/app/node_modules/@tiptap/react/dist/packages/react/src/Editor").Editor'.
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 2

### Browser Used

Chrome

### Expected Behavior

Build to be success

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
This should be resolved in 2.6.0

**Comment by nperez0111** [comment]
Also, this is a typescript error, you could fix it in your project if you wanted to

**Comment by nur-sasongko** [comment]
after i updated to 2.6.0 it still error which is from tiptap node modules folder

dashboard git:(master) ✗ npm run build  

> dashboard@0.0.0 build
> tsc && vite build

src/components/atoms/TextEditor/TextEditor.tsx:381:24 - error TS2322: Type 'import("/home/nur-sasongko/Documents/projects/node/motiolabs/learnhub/dashboard/node_modules/@tiptap/core/dist/packages/core/src/Editor").Editor | null' is not assignable to type 'import("/home/nur-sasongko/Documents/projects/node/motiolabs/learnhub/dashboard/node_modules/@tiptap/react/dist/packages/react/src/Editor").Editor | null'.
  Property 'contentComponent' is missing in type 'import("/home/nur-sasongko/Documents/projects/node/motiolabs/learnhub/dashboard/node_modules/@tiptap/core/dist/packages/core/src/Editor").Editor' but required in type 'import("/home/nur-sasongko/Documents/projects/node/motiolabs/learnhub/dashboard/node_modules/@tiptap/react/dist/packages/react/src/Editor").Editor'.

381         <EditorContent editor={editor} />
                           ~~~~~~

  node_modules/@tiptap/react/dist/packages/react/src/Editor.d.ts:12:5
    12     contentComponent: ContentComponent | null;
           ~~~~~~~~~~~~~~~~
    'contentComponent' is declared here.
  node_modules/@tiptap/react/dist/packages/react/src/EditorContent.d.ts:4:5
    4     editor: Editor | null;
          ~~~~~~
    The expected type comes from property 'editor' which is declared here on type 'IntrinsicAttributes & Omit<Omit<EditorContentProps, "ref"> & RefAttributes<HTMLDivElement>, "ref"> & { ...; }'


Found 1 error in src/components/atoms/TextEditor/TextEditor.tsx:381

**Comment by nur-sasongko** [comment]
i dunno what's wrong, and then i changed to 2.2.4 not ^2.2.4, build fine

**Comment by nperez0111** [comment]
Someone else reported the same thing: https://github.com/ueberdosis/tiptap/issues/5478

I'll get it fixed, you should not have to be on such an old version

**Comment by nur-sasongko** [comment]
Thank you man, i appreciate that!
